export const BaseUrl = `https://ammrha-production-v2.up.railway.app/api/v1`;

export const LOG_IN='/login'
export const USER =`/user`
export const Procedures =`/procedures`
export const BLACK_LIST =`/blacklist`
export const Departments =`/departments`
export const Available =`/available`
export const LIST =`/lists`
export const Criteria =`/criteria`
export const Announcement =`/announcement`
export const Create =`/create`
export const Delete =`/delete`
export const Update =`/update`
export const Ranks =`/ranks`
export const Volnteers =`/volunteers`
export const Dashbord =`/dashboard`
export const Stats =`/Stats`
export const Complaints =`/complaints`
export const Status =`/status`
export const Honor =`/honor-board`
export const HomePage =`/homePage`
export const Event =`/events`
export const Freezen = `/volunteer-freeze`
export const Transfer = `/transfer-department`
export const Position = `/assign-position`
export const STATUS =`/enums/statuses`
export const Type =`/enums/types`
export const TRANSFER =`/transfer-to-public`
export const Volunteer_Request =`/volunteer-requests`
export const Pinding = `/pending`
export const HR = `/HR`
export const finished = `/finished`
export const Intervews = `/interviews`
export const Finilize = `/finalize`
export const EXPORT = `/export`
export const DEACTIVE =`/deactivate`
export const EVALUTION =`/evaluations`
export const hr =`/hr`
export const PROFILE =`/profile`
export const ADMIN =`/admin`